// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"
#include "ui_Screen6.h"
#include "ui_Screen7.h"
#include "ui_Screen8.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * pat_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * anchon_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_new_background_png);    // assets/new_background.png
LV_IMG_DECLARE(ui_img_status_png);    // assets/status.png
LV_IMG_DECLARE(ui_img_selected_bg_png);    // assets/selected_bg.png
LV_IMG_DECLARE(ui_img_food_png);    // assets/food.png
LV_IMG_DECLARE(ui_img_game_png);    // assets/game.png
LV_IMG_DECLARE(ui_img_light_png);    // assets/light.png
LV_IMG_DECLARE(ui_img_med_png);    // assets/med.png
LV_IMG_DECLARE(ui_img_poop_png);    // assets/poop.png
LV_IMG_DECLARE(ui_img_spicy_png);    // assets/spicy.png
LV_IMG_DECLARE(ui_img_alert_png);    // assets/alert.png
LV_IMG_DECLARE(ui_img_an_chon1_png);    // assets/an_chon1.png
LV_IMG_DECLARE(ui_img_pat1_png);    // assets/pat1.png
LV_IMG_DECLARE(ui_img_pat2_png);    // assets/pat2.png
LV_IMG_DECLARE(ui_img_pat3_png);    // assets/pat3.png
LV_IMG_DECLARE(ui_img_pat5_png);    // assets/pat5.png
LV_IMG_DECLARE(ui_img_an_chon2_png);    // assets/an_chon2.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
