// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT statusBtn

lv_obj_t * ui_statusBtn_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_statusBtn;
    cui_statusBtn = lv_imgbtn_create(comp_parent);
    lv_imgbtn_set_src(cui_statusBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_status_png, NULL);
    lv_obj_set_width(cui_statusBtn, 19);
    lv_obj_set_height(cui_statusBtn, 25);
    lv_obj_set_x(cui_statusBtn, -50);
    lv_obj_set_y(cui_statusBtn, -44);
    lv_obj_set_align(cui_statusBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(cui_statusBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_STATUSBTN_NUM);
    children[UI_COMP_STATUSBTN_STATUSBTN] = cui_statusBtn;
    lv_obj_add_event_cb(cui_statusBtn, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_statusBtn, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_statusBtn_create_hook(cui_statusBtn);
    return cui_statusBtn;
}

