// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_STATUSBTN_H
#define _UI_COMP_STATUSBTN_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT statusBtn
#define UI_COMP_STATUSBTN_STATUSBTN 0
#define _UI_COMP_STATUSBTN_NUM 1
lv_obj_t * ui_statusBtn_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
