// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_MENUBAR_H
#define _UI_COMP_MENUBAR_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT menuBar
#define UI_COMP_MENUBAR_MENUBAR 0
#define UI_COMP_MENUBAR_STATUSBTN 1
#define UI_COMP_MENUBAR_FOODBTN 2
#define UI_COMP_MENUBAR_GAMEBTN 3
#define UI_COMP_MENUBAR_LIGHTBTN 4
#define UI_COMP_MENUBAR_MEDBTN 5
#define UI_COMP_MENUBAR_POOPBTN 6
#define UI_COMP_MENUBAR_SPICYBTN 7
#define UI_COMP_MENUBAR_ALERTBTN 8
#define _UI_COMP_MENUBAR_NUM 9
lv_obj_t * ui_menuBar_create(lv_obj_t * comp_parent);
void ui_event_comp_menuBar_menuBar(lv_event_t * e);
void ui_event_comp_menuBar_statusBtn(lv_event_t * e);
void ui_event_comp_menuBar_foodBtn(lv_event_t * e);
void ui_event_comp_menuBar_gameBtn(lv_event_t * e);
void ui_event_comp_menuBar_lightBtn(lv_event_t * e);
void ui_event_comp_menuBar_medBtn(lv_event_t * e);
void ui_event_comp_menuBar_poopBtn(lv_event_t * e);
void ui_event_comp_menuBar_spicyBtn(lv_event_t * e);
void ui_event_comp_menuBar_alertBtn(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
