// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_event_comp_menuBar_menuBar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_menuBar = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_comp_menuBar_statusBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_menuBar = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_comp_menuBar_foodBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_menuBar = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_comp_menuBar_gameBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_menuBar = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_comp_menuBar_lightBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_menuBar = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_comp_menuBar_medBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_menuBar = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_comp_menuBar_poopBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_menuBar = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen6_screen_init);
    }
}

void ui_event_comp_menuBar_spicyBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_menuBar = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen7_screen_init);
    }
}

void ui_event_comp_menuBar_alertBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_menuBar = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen8_screen_init);
    }
}

// COMPONENT menuBar

lv_obj_t * ui_menuBar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_menuBar;
    cui_menuBar = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_menuBar);
    lv_obj_set_width(cui_menuBar, 119);
    lv_obj_set_height(cui_menuBar, 125);
    lv_obj_set_x(cui_menuBar, -1);
    lv_obj_set_y(cui_menuBar, -1);
    lv_obj_set_align(cui_menuBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_menuBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_statusBtn;
    cui_statusBtn = lv_imgbtn_create(cui_menuBar);
    lv_imgbtn_set_src(cui_statusBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_status_png, NULL);
    lv_obj_set_width(cui_statusBtn, 21);
    lv_obj_set_height(cui_statusBtn, 25);
    lv_obj_set_x(cui_statusBtn, -50);
    lv_obj_set_y(cui_statusBtn, -44);
    lv_obj_set_align(cui_statusBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(cui_statusBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(cui_statusBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_foodBtn;
    cui_foodBtn = lv_imgbtn_create(cui_menuBar);
    lv_imgbtn_set_src(cui_foodBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_food_png, NULL);
    lv_obj_set_width(cui_foodBtn, 20);
    lv_obj_set_height(cui_foodBtn, 24);
    lv_obj_set_x(cui_foodBtn, -15);
    lv_obj_set_y(cui_foodBtn, -44);
    lv_obj_set_align(cui_foodBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(cui_foodBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(cui_foodBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_gameBtn;
    cui_gameBtn = lv_imgbtn_create(cui_menuBar);
    lv_imgbtn_set_src(cui_gameBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_game_png, NULL);
    lv_obj_set_width(cui_gameBtn, 19);
    lv_obj_set_height(cui_gameBtn, 23);
    lv_obj_set_x(cui_gameBtn, 18);
    lv_obj_set_y(cui_gameBtn, -45);
    lv_obj_set_align(cui_gameBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(cui_gameBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(cui_gameBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_lightBtn;
    cui_lightBtn = lv_imgbtn_create(cui_menuBar);
    lv_imgbtn_set_src(cui_lightBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_light_png, NULL);
    lv_obj_set_width(cui_lightBtn, 21);
    lv_obj_set_height(cui_lightBtn, 24);
    lv_obj_set_x(cui_lightBtn, 48);
    lv_obj_set_y(cui_lightBtn, -45);
    lv_obj_set_align(cui_lightBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(cui_lightBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(cui_lightBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_medBtn;
    cui_medBtn = lv_imgbtn_create(cui_menuBar);
    lv_imgbtn_set_src(cui_medBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_med_png, NULL);
    lv_obj_set_width(cui_medBtn, 19);
    lv_obj_set_height(cui_medBtn, 24);
    lv_obj_set_x(cui_medBtn, -47);
    lv_obj_set_y(cui_medBtn, 51);
    lv_obj_set_align(cui_medBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(cui_medBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(cui_medBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_poopBtn;
    cui_poopBtn = lv_imgbtn_create(cui_menuBar);
    lv_imgbtn_set_src(cui_poopBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_poop_png, NULL);
    lv_obj_set_width(cui_poopBtn, lv_pct(16));
    lv_obj_set_height(cui_poopBtn, lv_pct(20));
    lv_obj_set_x(cui_poopBtn, -16);
    lv_obj_set_y(cui_poopBtn, 50);
    lv_obj_set_align(cui_poopBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(cui_poopBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(cui_poopBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_spicyBtn;
    cui_spicyBtn = lv_imgbtn_create(cui_menuBar);
    lv_imgbtn_set_src(cui_spicyBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_spicy_png, NULL);
    lv_obj_set_width(cui_spicyBtn, 20);
    lv_obj_set_height(cui_spicyBtn, 24);
    lv_obj_set_x(cui_spicyBtn, 19);
    lv_obj_set_y(cui_spicyBtn, 51);
    lv_obj_set_align(cui_spicyBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(cui_spicyBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(cui_spicyBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t * cui_alertBtn;
    cui_alertBtn = lv_imgbtn_create(cui_menuBar);
    lv_imgbtn_set_src(cui_alertBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_alert_png, NULL);
    lv_obj_set_width(cui_alertBtn, 20);
    lv_obj_set_height(cui_alertBtn, 23);
    lv_obj_set_x(cui_alertBtn, 49);
    lv_obj_set_y(cui_alertBtn, 49);
    lv_obj_set_align(cui_alertBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(cui_alertBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(cui_alertBtn, &ui_img_selected_bg_png, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MENUBAR_NUM);
    children[UI_COMP_MENUBAR_MENUBAR] = cui_menuBar;
    children[UI_COMP_MENUBAR_STATUSBTN] = cui_statusBtn;
    children[UI_COMP_MENUBAR_FOODBTN] = cui_foodBtn;
    children[UI_COMP_MENUBAR_GAMEBTN] = cui_gameBtn;
    children[UI_COMP_MENUBAR_LIGHTBTN] = cui_lightBtn;
    children[UI_COMP_MENUBAR_MEDBTN] = cui_medBtn;
    children[UI_COMP_MENUBAR_POOPBTN] = cui_poopBtn;
    children[UI_COMP_MENUBAR_SPICYBTN] = cui_spicyBtn;
    children[UI_COMP_MENUBAR_ALERTBTN] = cui_alertBtn;
    lv_obj_add_event_cb(cui_menuBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_menuBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_statusBtn, ui_event_comp_menuBar_statusBtn, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_foodBtn, ui_event_comp_menuBar_foodBtn, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_gameBtn, ui_event_comp_menuBar_gameBtn, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_lightBtn, ui_event_comp_menuBar_lightBtn, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_medBtn, ui_event_comp_menuBar_medBtn, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_poopBtn, ui_event_comp_menuBar_poopBtn, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_spicyBtn, ui_event_comp_menuBar_spicyBtn, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_alertBtn, ui_event_comp_menuBar_alertBtn, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_menuBar, ui_event_comp_menuBar_menuBar, LV_EVENT_ALL, children);
    ui_comp_menuBar_create_hook(cui_menuBar);
    return cui_menuBar;
}

