// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_menuBar3 = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image6, &ui_img_new_background_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 345
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 345
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 100);

    ui_Label2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Light Screen");

    ui_menuBar3 = ui_menuBar_create(ui_Screen4);
    lv_obj_set_x(ui_menuBar3, -1);
    lv_obj_set_y(ui_menuBar3, -1);

    lv_obj_add_state(ui_comp_get_child(ui_menuBar3, UI_COMP_MENUBAR_LIGHTBTN), LV_STATE_FOCUSED);       /// States

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Image6 = NULL;
    ui_Label2 = NULL;
    ui_menuBar3 = NULL;

}
