// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_menuBar5 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image8, &ui_img_new_background_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 345
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 345
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 100);

    ui_menuBar5 = ui_menuBar_create(ui_Screen6);
    lv_obj_set_x(ui_menuBar5, -1);
    lv_obj_set_y(ui_menuBar5, -1);

    ui_Label5 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 1);
    lv_obj_set_y(ui_Label5, 2);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Poop Screen");

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_Image8 = NULL;
    ui_menuBar5 = NULL;
    ui_Label5 = NULL;

}
