// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_menuBar1 = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image3, &ui_img_new_background_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 345
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 345
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 100);

    ui_menuBar1 = ui_menuBar_create(ui_Screen2);
    lv_obj_set_x(ui_menuBar1, -1);
    lv_obj_set_y(ui_menuBar1, -1);

    lv_obj_add_state(ui_comp_get_child(ui_menuBar1, UI_COMP_MENUBAR_FOODBTN), LV_STATE_FOCUSED);       /// States
    lv_obj_set_style_bg_img_src(ui_comp_get_child(ui_menuBar1, UI_COMP_MENUBAR_FOODBTN), &ui_img_selected_bg_png,
                                LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(ui_comp_get_child(ui_menuBar1, UI_COMP_MENUBAR_FOODBTN), &ui_img_selected_bg_png,
                                LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Food Screen");

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image3 = NULL;
    ui_menuBar1 = NULL;
    ui_Label1 = NULL;

}
