// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_menuBar6 = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image9, &ui_img_new_background_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 345
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 345
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 100);

    ui_menuBar6 = ui_menuBar_create(ui_Screen7);
    lv_obj_set_x(ui_menuBar6, -1);
    lv_obj_set_y(ui_menuBar6, -1);

    ui_Label6 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 2);
    lv_obj_set_y(ui_Label6, 1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Spicy Screen");

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_Image9 = NULL;
    ui_menuBar6 = NULL;
    ui_Label6 = NULL;

}
