// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen8 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_menuBar7 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions

// build funtions

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_img_create(ui_Screen8);
    lv_img_set_src(ui_Image10, &ui_img_new_background_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 345
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 345
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image10, 100);

    ui_menuBar7 = ui_menuBar_create(ui_Screen8);
    lv_obj_set_x(ui_menuBar7, -1);
    lv_obj_set_y(ui_menuBar7, -1);

    ui_Label7 = lv_label_create(ui_Screen8);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 2);
    lv_obj_set_y(ui_Label7, -1);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Alert Screen");

}

void ui_Screen8_screen_destroy(void)
{
    if(ui_Screen8) lv_obj_del(ui_Screen8);

    // NULL screen variables
    ui_Screen8 = NULL;
    ui_Image10 = NULL;
    ui_menuBar7 = NULL;
    ui_Label7 = NULL;

}
